[package]
name = "canbusnoop"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3"
tokio-socketcan = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1" }
tokio-util = { version = "0.7", features = ["codec"] }
